set nocompatible

set rtp+=~/.vim/bundle/vundle/

call vundle#rc()

" Set comma to the leader key
let mapleader=','

if version >= 730
  Bundle 'Valloric/YouCompleteMe'
endif

Bundle 'monokrome/vim-user-configuration'

Bundle 'FredKSchott/CoVim'
Bundle 'LimpidTech/vimpy_examples'
Bundle 'Lokaltog/vim-easymotion'
Bundle 'Raimondi/delimitMate'
Bundle 'Shougo/unite.vim'
Bundle 'Shougo/vimproc.vim'
Bundle 'Valloric/YouCompleteMe'
Bundle 'airblade/vim-gitgutter'
Bundle 'altercation/vim-colors-solarized'
Bundle 'bling/vim-airline'
Bundle 'chrisbra/csv.vim'
Bundle 'digitaltoad/vim-jade'
Bundle 'drmingdrmer/xptemplate'
Bundle 'gmarik/vundle'
Bundle 'gregsexton/MatchTag'
Bundle 'h1mesuke/unite-outline'
Bundle 'jnwhiteh/vim-golang'
Bundle 'kchmck/vim-coffee-script'
Bundle 'lunaru/vim-less'
Bundle 'majutsushi/tagbar'
Bundle 'mattn/gist-vim'
Bundle 'mattn/webapi-vim'
Bundle 'michaeljsmith/vim-indent-object'
Bundle 'monokrome/vimpy'
Bundle 'mutewinter/nginx.vim'
Bundle 'nathanaelkane/vim-indent-guides'
Bundle 'neochrome/todo.vim'
Bundle 'othree/html5.vim'
Bundle 'plasticboy/vim-markdown'
Bundle 'scrooloose/nerdtree'
Bundle 'scrooloose/syntastic'
Bundle 'sjl/gundo.vim'
Bundle 'smerrill/vagrant-vim'
Bundle 'taxilian/a.vim'
Bundle 'terryma/vim-multiple-cursors'
Bundle 'tpope/heroku-remote'
Bundle 'tpope/vim-abolish'
Bundle 'tpope/vim-characterize'
Bundle 'tpope/vim-classpath'
Bundle 'tpope/vim-commentary'
Bundle 'tpope/vim-dispatch'
Bundle 'tpope/vim-endwise'
Bundle 'tpope/vim-eunuch'
Bundle 'tpope/vim-fireplace'
Bundle 'tpope/vim-flatfoot'
Bundle 'tpope/vim-fugitive'
Bundle 'tpope/vim-git'
Bundle 'tpope/vim-obsession'
Bundle 'tpope/vim-repeat'
Bundle 'tpope/vim-rhubarb'
Bundle 'tpope/vim-sensible'
Bundle 'tpope/vim-sleuth'
Bundle 'tpope/vim-speeddating'
Bundle 'tpope/vim-surround'
Bundle 'tpope/vim-tbone'
Bundle 'tpope/vim-unimpaired'
Bundle 'uggedal/go-vim'
Bundle 'vim-multiple-cursors'
Bundle 'vim-ruby/vim-ruby'
Bundle 'vim-scripts/Better-CSS-Syntax-for-Vim'
Bundle 'vim-scripts/EnhancedJumps'
Bundle 'vim-scripts/L9'
Bundle 'vim-scripts/TaskList.vim'
Bundle 'vim-scripts/VimClojure'
Bundle 'vim-scripts/closetag.vim'
Bundle 'vim-scripts/django.vim'
Bundle 'voithos/vim-python-matchit'
Bundle 'wavded/vim-stylus'

